//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONRVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipe()
        {
            this.Transports = new HashSet<Transport>();
            this.Volunteers = new HashSet<Volunteer>();
            this.VideosEquipes = new HashSet<VideosEquipe>();
        }
    
        public int Id { get; set; }
        public int SoireeId { get; set; }
        public int teamNumber { get; set; }
        public string organizationName { get; set; }
        public Nullable<int> mileage { get; set; }
        public Nullable<int> totalDonations { get; set; }
        public Nullable<int> completedTransportsCount { get; set; }
    
        public virtual Soiree Soiree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transport> Transports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Volunteer> Volunteers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideosEquipe> VideosEquipes { get; set; }
    }
}
