//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONRVideo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ONRCampagneVideoEntities : DbContext
    {
        public ONRCampagneVideoEntities()
            : base("name=ONRCampagneVideoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campagne> Campagnes { get; set; }
        public virtual DbSet<Centrale> Centrales { get; set; }
        public virtual DbSet<Equipe> Equipes { get; set; }
        public virtual DbSet<Soiree> Soirees { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
        public virtual DbSet<VideosEquipe> VideosEquipes { get; set; }
        public virtual DbSet<VideosOrganisation> VideosOrganisations { get; set; }
        public virtual DbSet<VideosSoiree> VideosSoirees { get; set; }
    }
}
