//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONRVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soiree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soiree()
        {
            this.Equipes = new HashSet<Equipe>();
        }
    
        public int Id { get; set; }
        public int campagneId { get; set; }
        public int central { get; set; }
        public System.DateTime soiree1 { get; set; }
    
        public virtual Campagne Campagne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipe> Equipes { get; set; }
    }
}
