//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONRVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEquipesSoireeTotaux
    {
        public int EquipeID { get; set; }
        public Nullable<int> TeamKM { get; set; }
        public int TeamNumber { get; set; }
        public Nullable<int> TeamDons { get; set; }
        public Nullable<int> TeamRaccompagnements { get; set; }
        public Nullable<int> KmSoiree { get; set; }
        public Nullable<int> TeamCountSoiree { get; set; }
        public Nullable<int> BenevolesSoiree { get; set; }
        public Nullable<int> TransportsSoiree { get; set; }
        public Nullable<int> DonsSoiree { get; set; }
        public System.DateTime SoireeDate { get; set; }
    }
}
