//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONRVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSoireesTotaux
    {
        public int SoireeId { get; set; }
        public Nullable<int> kmGROUP { get; set; }
        public Nullable<int> numberOFtEAMS { get; set; }
        public Nullable<int> transportsGroup { get; set; }
        public Nullable<int> donsGroup { get; set; }
    }
}
